/**
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.swagger.client.api

import io.swagger.client.model.ApiResponse
import java.io.File
import io.swagger.client.model.Pet
import io.swagger.client.ApiInvoker
import io.swagger.client.ApiException

import java.io.File
import java.util.Date

import scala.collection.mutable.HashMap
import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.core.check.ValidatorCheckBuilder
import io.gatling.http.check.HttpCheck
import io.gatling.http.response.Response

class PetApi(val defBasePath: String = "http://petstore.swagger.io/v2",
                        defApiInvoker: ApiInvoker = ApiInvoker) {
  var basePath = defBasePath
  var apiInvoker = defApiInvoker

  def addHeader(key: String, value: String) = apiInvoker.defaultHeaders += key -> value 

  /**
   * Add a new pet to the store
   * 
   * @param body Pet object that needs to be added to the store 
   * @return void
   */
  def addPet (body: Pet): io.gatling.http.request.builder.HttpRequestBuilder = {
    // create path and map variables
    val path = "/pet".replaceAllLiterally("\\{format\\}","json")
    val contentTypes = List("application/json", "application/xml", "application/json")
    val contentType = contentTypes(0)

    // query params
    val queryParams = new HashMap[String, String]
    val headerParams = new HashMap[String, String]
    val formParams = new HashMap[String, String]

    if (body == null) throw new Exception("Missing required parameter 'body' when calling PetApi->addPet")


    var postBody: AnyRef = body

    apiInvoker.invokeApi("addPet", basePath, path, "POST", queryParams.toMap, formParams.toMap, postBody, headerParams.toMap, contentType)
  }

  /**
   * Deletes a pet
   * 
   * @param petId Pet id to delete 
   * @param apiKey  (optional)
   * @return void
   */
  def deletePet (petId: Long, apiKey: String): io.gatling.http.request.builder.HttpRequestBuilder = {
    // create path and map variables
    val path = "/pet/{petId}".replaceAllLiterally("\\{format\\}","json")
      .replaceAllLiterally("{" + "petId" + "}",apiInvoker.escape(petId.toString))

    val contentTypes = List("application/json")
    val contentType = contentTypes(0)

    // query params
    val queryParams = new HashMap[String, String]
    val headerParams = new HashMap[String, String]
    val formParams = new HashMap[String, String]


    headerParams += "api_key" -> apiKey

    var postBody: AnyRef = null

    apiInvoker.invokeApi("deletePet", basePath, path, "DELETE", queryParams.toMap, formParams.toMap, postBody, headerParams.toMap, contentType)
  }

  /**
   * Finds Pets by status
   * Multiple status values can be provided with comma separated strings
   * @param status Status values that need to be considered for filter 
   * @return List[Pet]
   */
  def findPetsByStatus (status: List[String]): io.gatling.http.request.builder.HttpRequestBuilder = {
    // create path and map variables
    val path = "/pet/findByStatus".replaceAllLiterally("\\{format\\}","json")
    val contentTypes = List("application/json")
    val contentType = contentTypes(0)

    // query params
    val queryParams = new HashMap[String, String]
    val headerParams = new HashMap[String, String]
    val formParams = new HashMap[String, String]

    if (status == null) throw new Exception("Missing required parameter 'status' when calling PetApi->findPetsByStatus")

    if(String.valueOf(status) != "null") queryParams += "status" -> apiInvoker.serializeQueryParam(status)

    var postBody: AnyRef = null

    apiInvoker.invokeApi("findPetsByStatus", basePath, path, "GET", queryParams.toMap, formParams.toMap, postBody, headerParams.toMap, contentType)
  }

  /**
   * Finds Pets by tags
   * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
   * @param tags Tags to filter by 
   * @return List[Pet]
   */
  def findPetsByTags (tags: List[String]): io.gatling.http.request.builder.HttpRequestBuilder = {
    // create path and map variables
    val path = "/pet/findByTags".replaceAllLiterally("\\{format\\}","json")
    val contentTypes = List("application/json")
    val contentType = contentTypes(0)

    // query params
    val queryParams = new HashMap[String, String]
    val headerParams = new HashMap[String, String]
    val formParams = new HashMap[String, String]

    if (tags == null) throw new Exception("Missing required parameter 'tags' when calling PetApi->findPetsByTags")

    if(String.valueOf(tags) != "null") queryParams += "tags" -> apiInvoker.serializeQueryParam(tags)

    var postBody: AnyRef = null

    apiInvoker.invokeApi("findPetsByTags", basePath, path, "GET", queryParams.toMap, formParams.toMap, postBody, headerParams.toMap, contentType)
  }

  /**
   * Find pet by ID
   * Returns a single pet
   * @param petId ID of pet to return 
   * @return Pet
   */
  def getPetById (petId: Long): io.gatling.http.request.builder.HttpRequestBuilder = {
    // create path and map variables
    val path = "/pet/{petId}".replaceAllLiterally("\\{format\\}","json")
      .replaceAllLiterally("{" + "petId" + "}",apiInvoker.escape(petId.toString))

    val contentTypes = List("application/json")
    val contentType = contentTypes(0)

    // query params
    val queryParams = new HashMap[String, String]
    val headerParams = new HashMap[String, String]
    val formParams = new HashMap[String, String]


    var postBody: AnyRef = null

    apiInvoker.invokeApi("getPetById", basePath, path, "GET", queryParams.toMap, formParams.toMap, postBody, headerParams.toMap, contentType)
  }

  /**
   * Update an existing pet
   * 
   * @param body Pet object that needs to be added to the store 
   * @return void
   */
  def updatePet (body: Pet): io.gatling.http.request.builder.HttpRequestBuilder = {
    // create path and map variables
    val path = "/pet".replaceAllLiterally("\\{format\\}","json")
    val contentTypes = List("application/json", "application/xml", "application/json")
    val contentType = contentTypes(0)

    // query params
    val queryParams = new HashMap[String, String]
    val headerParams = new HashMap[String, String]
    val formParams = new HashMap[String, String]

    if (body == null) throw new Exception("Missing required parameter 'body' when calling PetApi->updatePet")


    var postBody: AnyRef = body

    apiInvoker.invokeApi("updatePet", basePath, path, "PUT", queryParams.toMap, formParams.toMap, postBody, headerParams.toMap, contentType)
  }

  /**
   * Updates a pet in the store with form data
   * 
   * @param petId ID of pet that needs to be updated 
   * @param name Updated name of the pet (optional)
   * @param status Updated status of the pet (optional)
   * @return void
   */
  def updatePetWithForm (petId: Long, name: String, status: String): io.gatling.http.request.builder.HttpRequestBuilder = {
    // create path and map variables
    val path = "/pet/{petId}".replaceAllLiterally("\\{format\\}","json")
      .replaceAllLiterally("{" + "petId" + "}",apiInvoker.escape(petId.toString))

    val contentTypes = List("application/x-www-form-urlencoded", "application/json")
    val contentType = contentTypes(0)

    // query params
    val queryParams = new HashMap[String, String]
    val headerParams = new HashMap[String, String]
    val formParams = new HashMap[String, String]


    var postBody: AnyRef = null

    apiInvoker.invokeApi("updatePetWithForm", basePath, path, "POST", queryParams.toMap, formParams.toMap, postBody, headerParams.toMap, contentType)
  }

  /**
   * uploads an image
   * 
   * @param petId ID of pet to update 
   * @param additionalMetadata Additional data to pass to server (optional)
   * @param file file to upload (optional)
   * @return ApiResponse
   */
  def uploadFile (petId: Long, additionalMetadata: String, file: File): io.gatling.http.request.builder.HttpRequestBuilder = {
    // create path and map variables
    val path = "/pet/{petId}/uploadImage".replaceAllLiterally("\\{format\\}","json")
      .replaceAllLiterally("{" + "petId" + "}",apiInvoker.escape(petId.toString))

    val contentTypes = List("multipart/form-data", "application/json")
    val contentType = contentTypes(0)

    // query params
    val queryParams = new HashMap[String, String]
    val headerParams = new HashMap[String, String]
    val formParams = new HashMap[String, String]


    var postBody: AnyRef = null

    apiInvoker.invokeApi("uploadFile", basePath, path, "POST", queryParams.toMap, formParams.toMap, postBody, headerParams.toMap, contentType)
  }
}

object PetApi {

  def findPetsByStatusResult[X](transformation: (List[Pet]) => X = identity[List[Pet]](_)): ValidatorCheckBuilder[HttpCheck,Response,String,X] = {
    val parser = (s: String) => ApiInvoker.deserialize(s, "array", classOf[Pet]).asInstanceOf[List[Pet]]
    bodyString
      .transform(parser)
      .transform(transformation)
  }

  def findPetsByTagsResult[X](transformation: (List[Pet]) => X = identity[List[Pet]](_)): ValidatorCheckBuilder[HttpCheck,Response,String,X] = {
    val parser = (s: String) => ApiInvoker.deserialize(s, "array", classOf[Pet]).asInstanceOf[List[Pet]]
    bodyString
      .transform(parser)
      .transform(transformation)
  }

  def getPetByIdResult[X](transformation: (Pet) => X = identity[Pet](_)): ValidatorCheckBuilder[HttpCheck,Response,String,X] = {
    val parser = (s: String) => ApiInvoker.deserialize(s, "", classOf[Pet]).asInstanceOf[Pet]
    bodyString
      .transform(parser)
      .transform(transformation)
  }

  def uploadFileResult[X](transformation: (ApiResponse) => X = identity[ApiResponse](_)): ValidatorCheckBuilder[HttpCheck,Response,String,X] = {
    val parser = (s: String) => ApiInvoker.deserialize(s, "", classOf[ApiResponse]).asInstanceOf[ApiResponse]
    bodyString
      .transform(parser)
      .transform(transformation)
  }
}
